[package]
name = "trash"
version = "0.0.2"
authors = ["timcryt <tymcrit@gmail.com>"]
edition = "2018"

[dependencies]
fnv = "1"
pest = "2"
pest_derive = "2.1"

[[bin]]
name = "trash"
path = "src/main.rs"

[lib]
name = "trash"
path = "src/lib.rs"