tuple = {"(" ~ " "* ~ (constr ~ " "+)* ~ constr* ~ ")"}
call  = {" "* ~ constr ~ " "* ~ (constr ~ " "+)* ~ constr*}
call_expr  = _{"[" ~ " "* ~ call ~ " "* ~ "]"}
line  = _{" "* ~ call? ~ "\n"}
clojure_inner = @{(" " | "\n")* ~ (call ~ "\n")* ~ call ~ (" " | "\n")*}
clojure = _{"{" ~ clojure_inner ~ "}"}

string = {('a'..'z' | '0'..'9' | 'A'..'Z' | "_")+}
ident = @{("$" |"@") ~ string}

constr = _{tuple | string | ident | call_expr | clojure}

code = {SOI ~ line* ~ call? ~ EOI}